name: newsapi-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - anthropic
    - requests
    - pydantic
    - pydantic-settings
    - python-dotenv
    - validators
    - pytest
    - pytest-cov
    - fastapi
    - uvicorn[standard]
    - httpx
